{% set name = "lb-nightly-rpc" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-rpc-{{ version }}.tar.gz
  sha256: 745115e3d81376162081ae44baab9ff1dc4a460be9294c3baaa2d6aa7289f872

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - celery >=5.1.2,<6.0.0
    - lb-nightly-configuration >=0.3,<1.0
    - lbplatformutils >=4.3.6,<5.0.0
    - mysqlclient >=2.0.3,<3.0.0
    - python >={{ python_min }},<4.0
    - requests >=2.28,<3.0.0

test:
  imports:
    - lb
    - lb.nightly.rpc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/lb-nightly-rpc/
  summary: Celery inter-process interface for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pikacic
    - maszyman
